// <auto-generated />
using System;
using AuditDemo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AuditDemo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260315061102_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("AuditDemo.Models.AuditSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FinancialYear")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FundName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AuditSessions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialYear = "2024-2025",
                            FundName = "Smith Family SMSF"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialYear = "2024-2025",
                            FundName = "Johnson Retirement Fund"
                        });
                });

            modelBuilder.Entity("AuditDemo.Models.ChecklistItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuditSessionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuditSessionId");

                    b.ToTable("ChecklistItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuditSessionId = 1,
                            Category = "Member Information",
                            Description = "Verify member details and TFNs",
                            IsCompleted = false,
                            Notes = ""
                        },
                        new
                        {
                            Id = 2,
                            AuditSessionId = 1,
                            Category = "Member Information",
                            Description = "Confirm member contributions within caps",
                            IsCompleted = false,
                            Notes = ""
                        },
                        new
                        {
                            Id = 3,
                            AuditSessionId = 1,
                            Category = "Member Information",
                            Description = "Check pension payment minimums met",
                            IsCompleted = false,
                            Notes = ""
                        },
                        new
                        {
                            Id = 4,
                            AuditSessionId = 1,
                            Category = "Financial Statements",
                            Description = "Review financial statements for accuracy",
                            IsCompleted = false,
                            Notes = ""
                        },
                        new
                        {
                            Id = 5,
                            AuditSessionId = 1,
                            Category = "Financial Statements",
                            Description = "Verify opening balances match prior year",
                            IsCompleted = false,
                            Notes = ""
                        },
                        new
                        {
                            Id = 6,
                            AuditSessionId = 1,
                            Category = "Financial Statements",
                            Description = "Confirm investment income correctly recorded",
                            IsCompleted = false,
                            Notes = ""
                        },
                        new
                        {
                            Id = 7,
                            AuditSessionId = 1,
                            Category = "Investments",
                            Description = "Confirm investments held in fund's name",
                            IsCompleted = false,
                            Notes = ""
                        },
                        new
                        {
                            Id = 8,
                            AuditSessionId = 1,
                            Category = "Investments",
                            Description = "Check sole purpose test compliance",
                            IsCompleted = false,
                            Notes = ""
                        },
                        new
                        {
                            Id = 9,
                            AuditSessionId = 1,
                            Category = "Investments",
                            Description = "Verify no in-house assets exceed 5% limit",
                            IsCompleted = false,
                            Notes = ""
                        },
                        new
                        {
                            Id = 10,
                            AuditSessionId = 1,
                            Category = "Compliance",
                            Description = "Confirm trust deed is up to date",
                            IsCompleted = false,
                            Notes = ""
                        },
                        new
                        {
                            Id = 11,
                            AuditSessionId = 1,
                            Category = "Compliance",
                            Description = "Check audit report lodged within deadlines",
                            IsCompleted = false,
                            Notes = ""
                        });
                });

            modelBuilder.Entity("AuditDemo.Models.ChecklistItem", b =>
                {
                    b.HasOne("AuditDemo.Models.AuditSession", "AuditSession")
                        .WithMany("ChecklistItems")
                        .HasForeignKey("AuditSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuditSession");
                });

            modelBuilder.Entity("AuditDemo.Models.AuditSession", b =>
                {
                    b.Navigation("ChecklistItems");
                });
#pragma warning restore 612, 618
        }
    }
}
